# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SJF.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 538)
        self.LabelNameProcess = QtWidgets.QLabel(Dialog)
        self.LabelNameProcess.setEnabled(True)
        self.LabelNameProcess.setGeometry(QtCore.QRect(10, 0, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelNameProcess.setFont(font)
        self.LabelNameProcess.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LabelNameProcess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelNameProcess.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LabelNameProcess.setTextFormat(QtCore.Qt.PlainText)
        self.LabelNameProcess.setObjectName("LabelNameProcess")
        self.lineNameProceso = QtWidgets.QLineEdit(Dialog)
        self.lineNameProceso.setGeometry(QtCore.QRect(10, 30, 261, 27))
        self.lineNameProceso.setObjectName("lineNameProceso")
        self.ButtonProces = QtWidgets.QPushButton(Dialog)
        self.ButtonProces.setGeometry(QtCore.QRect(300, 60, 87, 27))
        self.ButtonProces.setObjectName("ButtonProces")
        self.LabelProcess = QtWidgets.QLabel(Dialog)
        self.LabelProcess.setEnabled(True)
        self.LabelProcess.setGeometry(QtCore.QRect(10, 70, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelProcess.setFont(font)
        self.LabelProcess.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LabelProcess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelProcess.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LabelProcess.setTextFormat(QtCore.Qt.PlainText)
        self.LabelProcess.setObjectName("LabelProcess")
        self.lineProceso = QtWidgets.QLineEdit(Dialog)
        self.lineProceso.setGeometry(QtCore.QRect(10, 100, 261, 27))
        self.lineProceso.setObjectName("lineProceso")
        self.scrollAreaProcess = QtWidgets.QScrollArea(Dialog)
        self.scrollAreaProcess.setGeometry(QtCore.QRect(10, 170, 261, 111))
        self.scrollAreaProcess.setWidgetResizable(True)
        self.scrollAreaProcess.setObjectName("scrollAreaProcess")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaProcess.setWidget(self.scrollAreaWidgetContents)
        self.LabelProcess_2 = QtWidgets.QLabel(Dialog)
        self.LabelProcess_2.setEnabled(True)
        self.LabelProcess_2.setGeometry(QtCore.QRect(10, 140, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelProcess_2.setFont(font)
        self.LabelProcess_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LabelProcess_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelProcess_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LabelProcess_2.setTextFormat(QtCore.Qt.PlainText)
        self.LabelProcess_2.setObjectName("LabelProcess_2")
        self.textBrowserInProcess = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserInProcess.setGeometry(QtCore.QRect(10, 320, 256, 192))
        self.textBrowserInProcess.setObjectName("textBrowserInProcess")
        self.LabelProcess_3 = QtWidgets.QLabel(Dialog)
        self.LabelProcess_3.setEnabled(True)
        self.LabelProcess_3.setGeometry(QtCore.QRect(10, 290, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelProcess_3.setFont(font)
        self.LabelProcess_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LabelProcess_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelProcess_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LabelProcess_3.setTextFormat(QtCore.Qt.PlainText)
        self.LabelProcess_3.setObjectName("LabelProcess_3")

        self.retranslateUi(Dialog)
        self.ButtonProces.clicked.connect(self.lineNameProceso.copy) # type: ignore
        self.ButtonProces.clicked.connect(self.lineProceso.copy) # type: ignore
        self.ButtonProces.clicked.connect(self.lineNameProceso.clear) # type: ignore
        self.ButtonProces.clicked.connect(self.lineProceso.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LabelNameProcess.setText(_translate("Dialog", "Inserte nombre del un Proceso"))
        self.ButtonProces.setText(_translate("Dialog", "INSERT"))
        self.LabelProcess.setText(_translate("Dialog", "Inserte tiempo del Proceso"))
        self.LabelProcess_2.setText(_translate("Dialog", "Lista de Procesos"))
        self.LabelProcess_3.setText(_translate("Dialog", "Proceso en Ejecución"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
