# -*- coding: utf-8 -*-

# Form implementation  generated from reading ui file 'mesa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mesa_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(753, 543)
        self.pushButtonComer = QtWidgets.QPushButton(Dialog)
        self.pushButtonComer.setGeometry(QtCore.QRect(590, 50, 87, 27))
        self.pushButtonComer.setObjectName("pushButtonComer")
        self.pushButtonNoComer = QtWidgets.QPushButton(Dialog)
        self.pushButtonNoComer.setGeometry(QtCore.QRect(590, 100, 87, 27))
        self.pushButtonNoComer.setObjectName("pushButtonNoComer")
        self.labelmesa = QtWidgets.QLabel(Dialog)
        self.labelmesa.setGeometry(QtCore.QRect(50, 20, 531, 501))
        self.labelmesa.setText("")
        self.labelmesa.setPixmap(QtGui.QPixmap(":/mesas/3mesa.png"))
        self.labelmesa.setObjectName("labelmesa")
        self.labelFilo0 = QtWidgets.QLabel(Dialog)
        self.labelFilo0.setGeometry(QtCore.QRect(140, 190, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelFilo0.setFont(font)
        self.labelFilo0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilo0.setObjectName("labelFilo0")
        self.labelFilo1 = QtWidgets.QLabel(Dialog)
        self.labelFilo1.setGeometry(QtCore.QRect(200, 360, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelFilo1.setFont(font)
        self.labelFilo1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilo1.setObjectName("labelFilo1")
        self.labelFilo2 = QtWidgets.QLabel(Dialog)
        self.labelFilo2.setGeometry(QtCore.QRect(360, 360, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelFilo2.setFont(font)
        self.labelFilo2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilo2.setObjectName("labelFilo2")
        self.labelFilo3 = QtWidgets.QLabel(Dialog)
        self.labelFilo3.setGeometry(QtCore.QRect(420, 190, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelFilo3.setFont(font)
        self.labelFilo3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilo3.setObjectName("labelFilo3")
        self.labelFilo4 = QtWidgets.QLabel(Dialog)
        self.labelFilo4.setGeometry(QtCore.QRect(280, 70, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelFilo4.setFont(font)
        self.labelFilo4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilo4.setObjectName("labelFilo4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonComer.setText(_translate("Dialog", "Comer"))
        self.pushButtonNoComer.setText(_translate("Dialog", "No Comer"))
        self.labelFilo0.setText(_translate("Dialog", "1"))
        self.labelFilo1.setText(_translate("Dialog", "2"))
        self.labelFilo2.setText(_translate("Dialog", "3"))
        self.labelFilo3.setText(_translate("Dialog", "4"))
        self.labelFilo4.setText(_translate("Dialog", "5"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
